name: Release Drafter

on:
  push:
    branches:
      - develop
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  autolabel:
    if: github.event_name == 'pull_request_target' && github.event.action != 'labeled' && github.event.action != 'unlabeled'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
